### ISSUE TITLE
Error: Unbound module Base64

### ISSUE THREAD

**Issue by olafhering** [ocaml/opam#5232]
Commit f229f060eed148c2bf44dbc034898c5994f4c42c and 4a71a5fef0a9f1e48486298d8c689d2a7ab452c5 added usage of some `Base64` module, but failed to add the proper build dependencies. It happened to work by luck because `extlib` included such a module.

With the switch to dune, this still happened to work because extlib up to 1.7.8 included its own `Base64` module.

Starting with ygrek/ocaml-extlib#53, and extlib 1.7.9 in ocaml/opam-repository#21946, `Base64` is not included anymore. As a result building of opam fails. Due to shortcomings in the opam-repository CI, this issue was not noticed, and the extlib upgrade was merged.

The actual error is:
````
dune build --verbose --for-release-of-packages=opam-admin,opam-client,opam-core,opam-format,opam-installer,opam-repository,opam-solver,opam-state,opam -j8 @install
....
[   17s] Command [393] exited with code 2:
[   17s] $ (cd _build/default && /usr/bin/ocamlc.opt -w -40 -w +a-4-40-42-44-48 -safe-string -w -67 -g -bin-annot -I src/client/.opam_client.objs/byte -I /usr/lib64/ocaml/cmdliner -I /usr/lib64/ocaml/cudf -I /usr/lib64/ocaml/dose3/algo -I /usr/lib64/ocaml/dose3/common -I /usr/lib64/ocaml/extlib -I /usr/lib64/ocaml/mccs -I /usr/lib64/ocaml/mccs/glpk/internal -I /usr/lib64/ocaml/ocamlgraph -I /usr/lib64/ocaml/opam-file-format -I /usr/lib64/ocaml/re -I /usr/lib64/ocaml/re/pcre -I /usr/lib64/ocaml/seq -I /usr/lib64/ocaml/stdlib-shims -I src/core/.opam_core.objs/byte -I src/format/.opam_format.objs/byte -I src/repository/.opam_repository.objs/byte -I src/solver/.opam_solver.objs/byte -I src/state/.opam_state.objs/byte -intf-suffix .ml -no-alias-deps -o src/client/.opam_client.objs/byte/opamSwitchCommand.cmo -c -impl src/client/opamSwitchCommand.ml)
[   17s] File "src/client/opamSwitchCommand.ml", line 403, characters 18-38:
[   17s] 403 |       let value = Base64.decode_string content in
[   17s]                         ^^^^^^^^^^^^^^^^^^^^
[   17s] Error: Unbound module Base64
````
I think the fix is to adjust the relevant `dune` file to rely on the standalone `base64` module, which exists since ocaml/opam-repository#18109, and to update the relevant opam files to actually pull it in unconditionally.

Thanks.

**Comment by kit-ty-kate** [comment]
Which version of opam are you trying to compile? The `2.1` and `2.0` branches are not compatible with extlib >= 1.7.8 (it is written down in its opam file) but `master` should compile perfectly

**Comment by olafhering** [comment]
This is commit 1388025221bf807ae9cfe5c5bb274d1edee6a3c2, which happens to work fine with extlib 1.7.8 AFAICS.

Which commit in `master` is supposed to address the `Base64` failure? Looks like 4d8229ef139b8431a10b468ead2f4e7fc5f35f4c may address this failure.

**Comment by kit-ty-kate** [comment]
> Which commit in `master` is supposed to address the `Base64` failure? Looks like [4d8229e](https://github.com/ocaml/opam/commit/4d8229ef139b8431a10b468ead2f4e7fc5f35f4c) may address this failure.

indeed, it is.

> This is commit [1388025](https://github.com/ocaml/opam/commit/1388025221bf807ae9cfe5c5bb274d1edee6a3c2), which happens to work fine with extlib 1.7.8 AFAICS.

no it shouldn't. I suspect you are installing extlib manually without `minimal=1`? Because the normal `extlib` package will not work.

**Comment by olafhering** [comment]
At least opam's `configure` seems to fail at recognizing all required packages. Perhaps just a cosmetic side effect due to lack of findlib in the build chroot.
I will backport the Base64 commit referenced above, this will most likely address it. Sorry for not checking for changes in the `master` branch before reporting the failure.
`extlib` is built with dune, no idea how to specify `minimal`.

**Comment by kit-ty-kate** [comment]
> `extlib` is built with dune, no idea how to specify `minimal`.

I mean for 1.7.8 (`make minimal=1`)
Dune is only the new build system since 1.7.9, which made the equivalent of `minimal=1` the only default so that's why you're only hitting the issue now.

In opam-repository, `extlib` was split a long time ago (2013) into `extlib` (which builds it with `minimal=1`, which does not install or compile the possibly conflicting module names, e.g. `unzip`, …) and `extlib-compat` which ships every modules even the conflicting ones. The breaking change in 1.7.8 was to add `Base64` to the list of conflicting modules

**Comment by olafhering** [comment]
I backported 4d8229ef139b8431a10b468ead2f4e7fc5f35f4c, which fixed the build failure.

Sorry again for not checking `master` branch first.
